FROM nginx:1.26-alpine
RUN rm /etc/nginx/conf.d/default.conf

# 설정 파일 복사
COPY default.conf /etc/nginx/conf.d/default.conf

# HTML 파일들 복사
COPY ./index.html /usr/share/nginx/html/index.html
COPY ./company.html /usr/share/nginx/html/company.html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]